name: Build and Test Python Calculator

on:
  push:
    branches: [ "develop", "feature/*" ]

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run unittests
        run: |
          python -m unittest discover -v
